---
#
# This playbook creates configs, but will not deploy them
#
- name: Build ACL configuration
  hosts: ACL_TEST
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    fabric_dir_name: "ACL_TEST"
    execute_tasks: false
  tasks:
    - name: 'reset local folders for output'
      tags: [build, generate]
      import_role:
        name: arista.avd.build_output_folders

    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: eos_cli_config_gen
